### ISSUE TITLE
Make `/<FEN>` endpoint better

### ISSUE THREAD

**Issue by rootEnginear** [rootEnginear/why-is-this-a-checkmate#2]
Current implementation of `/<FEN>` which is:
```js
app.get("/:a/:b/:c/:d/:e/:f/:g/:h", (req, res) => {
  const { a, b, c, d, e, f, g, h } = req.params;
  res.redirect(`/?fen=${[a, b, c, d, e, f, g, h].join("/")}`);
});
```
is kind of ugly, maybe refactor this or change how it accepts params.

**Comment by casperx** [comment]
Interesting. You can count on me to complete it. Do you mind giving me this problem?
